{ lib, config, pkgs, ... }:

{

  imports = [
    # overriding package sets and such
    ./modules/nixpkgs-configuration.nix

    # the results of the hardware scan generated by nixos-install
    ./modules/hardware-configuration.nix

    # bootloader, zfs, etc.
    ./modules/boot-and-filesystems.nix

    # networking setup
    ./modules/networking.nix

    # video, graphics
    ./modules/graphics.nix

    # audio, sound
    ./modules/sound.nix

    # services
    ./modules/services.nix

    # home-manager NixOS module
    <home-manager/nixos>

    # home-manager setup for the primary user
    ./users/rizoid
  ];

  documentation.dev.enable = true;
  documentation.doc.enable = true;
  nixpkgs.config.allowUnfree = true;

  hardware.cpu.intel.updateMicrocode = true;

  fonts.fonts = with pkgs; [
    input-fonts
    fira-code
    fira-code-symbols
  ];

  environment.systemPackages = with pkgs; [
    xorg.xrandr
    xorg.xf86inputkeyboard
    xorg.xf86inputlibinput
	  xorg.xf86inputmouse
	  xorg.xinput
  ];

  # Select internationalisation properties.
  console = {
    font   = "Lat2-Terminus16";
    keyMap = "us";
  };

  # TODO set currency etc
  # TODO should we do this at the home-manager level?
  # probably not but still
  i18n.defaultLocale = "en_US.UTF-8";

  # Set your time zone.
  time.timeZone = "America/Chicago";

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "19.09"; # Did you read the comment?

}
